### ISSUE TITLE
Cannot login to private server, throws Error: Not Authorized

### ISSUE THREAD

**Issue by barthogenes** [screepers/screeps-multimeter#45]
When I start the private server via the Steam UI, call `setPassword("BBCorn", "1234")` and then try to start multimeter using `multimeter -s private`, I get `Error: Not Authorized`.

My `.screeps.yaml`:
```
servers:
  main:
    host: screeps.com
    secure: true
    token: '00000000-0a0a-0a00-000a-a0000a0000a0'
  ptr:
    host: screeps.com
    secure: true
    path: '/ptr'
    token: '00000000-0a0a-0a00-000a-a0000a0000a0'
  season:
    host: screeps.com
    secure: true
    path: '/season'
    token: '00000000-0a0a-0a00-000a-a0000a0000a0'
  private:
    host: 127.0.0.1
    port: 21025
    secure: false
    username: BBCorn
    password: 1234
  configs:
  multimeter:
    plugins: []
    aliases: {}
    logFilename: 'multimeter.log'
```

It does work if I make the same request with a REST Client:
![image](https://user-images.githubusercontent.com/20557666/119594625-6df29000-bddc-11eb-9e79-d09ad45ee9bc.png)

Am I doing something wrong?
